### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by mkhan-coremedia** [heseba/wotdl2api#1]
It mentions requirements.txt but it is missing

**Comment by heseba** [comment]
Oh you're right. We have migrated to pipenv, so you need to use the Pipfile instead. I will update the README accordingly. Thanks for the hint.

**Comment by heseba** [comment]
fixed:
https://github.com/heseba/wotdl2api/commit/ff4f76d66b45c74d318a6e0701e0decd40623e76
